### ISSUE TITLE
backup history from deleted account

### ISSUE THREAD

**Issue by mahdi007** [tvdstaaij/telegram-history-dump#14]
My problem is that  deleted accounts hasn't named to insert in "backup_users" array in config file ,their has named in dialog_list ex: "deleted  user#123456789" I tested this name but not working
 And in the other hand if I fill empty array, in "Backing up dialogs" this deleted accounts doesn't exist.
 So how can I backup history from deleted account?

**Comment by tvdstaaij** [comment]
Based on earlier experience with telegram-cli I thought it wasn't possible to recover messages from dialogs with deleted users, but it turns out I was wrong and committed a patch to make this possible. If you pull in the latest master revision you should be able to backup these dialogs either by leaving the array empty or by adding strings like `'user#123456789'`.

Thanks for reporting this!

**Comment by mahdi007** [comment]
Great it worked! Thanks for this awesome script :)

**Comment by Jimmm** [comment]
didn't work with normal groups

**Comment by Jimmm** [comment]
also not working with users IDs
