### ISSUE TITLE
Is it possible to download only media?

### ISSUE THREAD

**Issue by kiddick** [tvdstaaij/telegram-history-dump#18]

**Comment by tvdstaaij** [comment]
All messages have to be fetched from Telegram in order to download the associated media files. It would technically be possible to not save them in json files of course, but it won't speed the process up or anything like that. Is speed the reason behind your question or is there some other reason you don't want the message data?

**Comment by kiddick** [comment]
Yeah, it is about speed.
Thanks for clarification.

To not duplicate issues there are two more questions:
1) I've fetched about 150k messages, and at the final step my system hung and after some time processes with script and tg-cli was killed (although I haven't specified -k option).
But looks like history is ok since first and list messages are the same as in telegram apps?
Do you have any experience and thoughts about it, why it is happen and may I miss something?

2) About messages with link to images. As you know telegram always tries to fetch image and show it into client app. So is it possible to download that "attachment"?

**Comment by tvdstaaij** [comment]
1) I can backup my 250k messages in one go without a problem, so just the amount of messages is probably not the issue. There are quite a few bugs in telegram-cli unfortunately, you may have triggered one of them (especially if telegram-cli exited with a failed assertion or the message "signal received"). You can try taking out the user/group that was about to be backed up before the crash.

2) I'm not sure how this works and haven't found anything relevant in the API documentation so far. But it's safe to say that telegram-cli does not implement this and probably will not implement it since previews are not very relevant for a command line utility. I think your best option would be to download the image URLs with your own script.
