### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by mohsengit** [tvdstaaij/telegram-history-dump#20]
Hi, Thanks for all your help.
 
I run the whole thing successfully! Outputs only Json files even aftee I uncomment formatters... doesnt matter which I I uncomment (use) nothing other than the Json file is made Can you please help me?

Thanks again
M

**Comment by tvdstaaij** [comment]
Can you provide the following (with any personal information omitted of course):

* The contents of your config.yaml
* The script's output
* The output of the shell command `ls -l output`

**Comment by mohsengit** [comment]
Hi - Thanks for the quick reply. it turns out I was just being stupid! 

Please note **others**:

When you change the config file and remove the "#" press space again to put the line EXACTLY where it was as if you change the location / or move the Formatters it will not work. Just DELETE the "#" and press "Space" to compensate the deleted "#" space. Hope that made sense.

:)

**Comment by tvdstaaij** [comment]
Yeah I suspected something like this, it happens because the indentation level matters in YAML for the object nesting. You're not the first one to run into this (#11), I'm considering making the object nesting explicit with `{` and `}` like in JSON (YAML is a superset of JSON so this is allowed, just not required) so that it will be much harder to accidentally change the nesting levels.

**Comment by tvdstaaij** [comment]
The above change has been implemented in the v2.1.0 release, it is now much less likely that something like this will happen as a result of imperfect indentation.
