### ISSUE TITLE
Backup chats by chat ids

### ISSUE THREAD

**Issue by araishikeiwai** [tvdstaaij/telegram-history-dump#28]
Hi @tvdstaaij thank you for the great tool!

I have a question about backing up chats (I could try it myself but right now I'm dumping chats which has taken so long and probably will take more time).

What if I want to setup which chat/group to backup by their chat ids? Since many of my groups have 'very dynamic' chat titles (the title may change up to 10 times a day :joy:)

I was thinking about writing the ids to the YAML file and then start the tg-cli with --disable-names option.

Will that work?

**Comment by WeidzM** [comment]
+1 Can't dump a group because of the name change
(Can't resume after rename folders/files either :/)

**Comment by tvdstaaij** [comment]
This is a very relevant issue, I've had some trouble with changing chat names myself as well, it would be good to do something about this for the next release.

I can easily make it so that IDs are also accepted in the target arrays, no need for additional options I think. The question is what to do with the JSON filenames when using incremental backup. Currently it works like this:
* When doing the initial backup, the JSON file is named after the dialog title in that point in time. Both the dialog ID and the generated filename are stored in `progress.json`.
* Further incremental backups only use the ID, the filename is looked up from `progress.json`. This means that when the title changes, the new messages are still appended to the correct file, although the filename is never updated.

I can think of the following options:
* Keep the current behavior. Advantage: consistent and readable filenames, disadvantage: filenames are not kept up-to-date.
* Use IDs as filenames. Advantage: consistent filenames, disadvantage: unfriendly filenames.
* Automatically rename files. Advantage: filenames are human friendly and always up-to-date, disadvantage: filenames randomly change, can be a problem for automated processing.

Any thoughts / suggestions?

@WeidzM You can actually manually change the name of the file as it is now (although it isn't necessary for correct incremental backups), but you have to edit `progress.json` as well to reflect the new filename.

**Comment by araishikeiwai** [comment]
I'd prefer the IDs as filenames as I have automated scripts as well for processing the backups.
However, some people prefer the other. How about making one default, and the others as options when running the script?

**Comment by tvdstaaij** [comment]
I hadn't really considered that, but clearly there are multiple use cases that have to be facilitated, so I think a configuration setting would be acceptable here.

**Comment by tvdstaaij** [comment]
With the latest master it is now possible to select chats by peer_id (commit 3452434) and achieve all of the above mentioned json file naming options (commit 0b4d006). I believe this resolves all points in this issue, feedback is welcome.

**Comment by araishikeiwai** [comment]
great! will try the new version out
