### ISSUE TITLE
Absolute path for backup_dir

### ISSUE THREAD

**Issue by araishikeiwai** [tvdstaaij/telegram-history-dump#29]
Hi,

I set the `backup_dir` in config-yaml to:

`backup_dir: '/home/araishikeiwai/Google Drive/Others/Telegram Backups'`

But the output is stored in `./home/araishikeiwai/Google Drive/Others/Telegram Backups` (relative path)

**EDIT**

I misread the line:
`# It his is a relative path it will be relative to the script's directory`

Did you mean "if this is a" or "this is a"?

If the latter, could you make it so that we can provide absolute path?

**Comment by tvdstaaij** [comment]
It looks like I intended to support both absolute and relative (the sentence should definitely read "if this is") but ended up not implementing support for absolute, and didn't notice because I use relative myself.

The relevant code is [this oneliner function](https://github.com/tvdstaaij/telegram-history-dump/blob/5fe9ba5fb9585e626a46943bb1ba82e4c35285a1/lib/util.rb#L19). It would need to just return the path if it is absolute, and otherwise do what it does now. You can send a PR if you want, otherwise I'll do it myself when I have time.

**Comment by araishikeiwai** [comment]
i created a PR in #30 for this issue

**Comment by araishikeiwai** [comment]
fixed in above PR, closing it
