### ISSUE TITLE
PISG Output: Gives Random Usernames?`

### ISSUE THREAD

**Issue by nikhiljha** [tvdstaaij/telegram-history-dump#36]
The usernames in PISG formatted logs look like:

uRANDOMSTRING8hUW*EYHEOewq

That's all.

**Comment by tvdstaaij** [comment]
This is by design. The formatter also outputs an XML PISG configuration snippet that maps the user IDs to their real (user)names when running PISG. I did this for compatibility; there are many characters allowed in Telegram (user)names that are illegal in IRC.

If you have a use case for this formatter that requires real names, and/or does not involve running PISG (I think it could choke on the names if they aren't IRC compatible, but haven't actually tested), I could add an option to get the actual names.

**Comment by nikhiljha** [comment]
When I parse with pisg the names are unintelligible, which is the problem.

If I go to the html file it makes it says"uRANDOmSTUFF" instead of the names of the people on telegram.

**Comment by nikhiljha** [comment]
I guess I just have to `cat usernames.cfg >> pisg.cfg` and test it? I will try in a bit. Thanks for helping.

**Comment by nikhiljha** [comment]
usermap.cfg is blank...

**Comment by nikhiljha** [comment]
Nevermind that's my fault. Got it to work, thanks!
