### ISSUE TITLE
Store history by ID/username instead of display name?

### ISSUE THREAD

**Issue by AndrewNeo** [tvdstaaij/telegram-history-dump#42]
Is it possible to make this store the chat history by username or user ID instead of the display name? Most of my friends change their display names rather regularly, so it throws off properly appending to their old logs on a subsequent incremental backup. Keeping a map of username/ID/display name could be used to convert it to display name for things like the HTML output.

**Comment by tvdstaaij** [comment]
The chats are actually tracked by Telegram ID internally in `progress.json`. The json filenames are just "for show"; the filename is picked in the first backup based on the display name at that moment, then stored in `progress.json` so that the same file is always used for the same dialog even if the name changes. This naming scheme keeps filenames both consistent and readable at the expense of not keeping them up-to-date. I would like to implement other naming schemes as well, this is discussed in #28. I haven't found time to work on this issue yet.

Another issue is that when backups are done selectively (with a list of partial dialog names), the dialogs will be excluded when the name changes too significantly, so the name list has to be updated every time this happens. This is also covered by #28.

If you meant neither of the above points (fixed filenames, selection based on display name) and actually observed that new messages of an existing dialog are dumped to a different file: that is definitely not supposed to happen. Can you check `progress.json` to see if it makes sense or not? Each dialog in the backup should be listed there exactly once, keyed by a unique ID (numeric or hex), and refer to one "outfile" in the output directory (which may be an old name of the dialog).

**Comment by tvdstaaij** [comment]
Should now be resolved, see #28. Closing this, further discussion can take place there if necessary.
