### ISSUE TITLE
Relative media paths

### ISSUE THREAD

**Issue by feklee** [tvdstaaij/telegram-history-dump#52]
Excerpt from `output/json/john_doe.jsonl`:

    {"event":"message","id":"010000008d6ba40c4104000000000000c4a5a5cf527658c5","flags":256,"from":{"id":"$010000008d6ba40cc4a5a5d536234sb6","peer_type":"user","peer_id":3634534f9,"print_name":"John_Doe","flags":65537,"first_name":"John","when":"2016-11-28 22:39:35","last_name":"Doe","phone":"4917661903543"},"to":{"id":"$0100000018ec6a110aca4f3645aff3d6","peer_type":"user","peer_id":292223423,"print_name":"Foo_Bar","flags":524289,"first_name":"Foo","when":"2016-11-28 22:39:53","last_name":"Bar","phone":"491741344354","username":"foobar"},"out":false,"unread":false,"service":false,"date":1480176787,"media":{"type":"photo","caption":"","file":"/home/foobar/telegram-history-dump/output/media/John_Doe/download_535454028_154356.jpg"}}

Note the absolute path:

    /home/foobar/telegram-history-dump/output/media/John_Doe/download_535454028_154356.jpg

Absolute media paths break when migrating output to a different location. *Is it possible to let the tool use relative paths?*

**Comment by tvdstaaij** [comment]
This is fairly trivial, here's [a patch](https://github.com/tvdstaaij/telegram-history-dump/commit/e564200628e238966472a47f221721179eea8c45) that does this when copy_media is set to true (if not, relative paths wouldn't make sense because the telegram-cli cache directory is typically in a completely different place and system-dependent by nature). With this patch you would get `media/John_Doe/download_535454028_154356.jpg`.

I'm not yet sure whether to make this the default behavior, because absolute paths tend to be reliable and it's consistent with the behavior for copy_media=false. I'm also reluctant to add yet another path related option. But you do have a valid point that absolute paths are pointless if you're planning on archiving the backup with media and all on a different machine.

**Comment by feklee** [comment]
Thanks for the patch!
