### ISSUE TITLE
JSONL / conversation / day

### ISSUE THREAD

**Issue by feklee** [tvdstaaij/telegram-history-dump#53]
The JSONL format is nice. However, files get big, and I would like to process (encrypt) them on a daily basis. I looked at the output of the plain text formatter, but that misses a lot of meta data.

*Is it possible to have one JSONL file per conversation per day?*

**Comment by tvdstaaij** [comment]
It would be trivial to create a formatter that outputs JSONL files per day, but as with all formatters, it would still require the original large JSONL files to be kept (at least if you want it to work with incremental backups). So based on your description I think this is not what you're looking for.

I do have an alternative idea. You could:

* Do an initial backup run, possibly split the JSONL output to daily files yourself if you want the entire archive to be daily, run them through your process and store somewhere else
* Blank the JSONL files in the telegram-history-dump output directory (not remove, because the script expects the files to exist after the initial run)
* Do a backup run every following day (e.g. around midnight), and again process the files, store them somewhere else and blank the originals

Due to the saved progress in progress.json, this will result in daily incremental backups that you can process individually. There is one gotcha: if you miss one or more days because your script breaks or something, and then backup again, you'll get files with more than one day's worth of messages. If this risk is a problem you could deal with it by splitting the JSONL files to multiple files based on message date before doing the rest of the processing.

**Comment by feklee** [comment]
Thanks for the suggestions! In fact I was thinking about blanking the JSONL files. Perhaps I’ll update my current backup script:

    #!/bin/bash
    
    # Backs up my Telegram account "******".
    
    # `telegram-cli` needs to run on port 9009.
    
    # Felix E. Klee <felix.klee@inka.de>
    
    ROOT="$HOME/telegram_backup"
    
    "$ROOT/telegram-history-dump/telegram-history-dump.rb" \
        --config="$HOME/telegram_backup/config.yaml"
    
    cd "$ROOT/output"
    
    REC=felix.klee@inka.de
    
    # Encrypts files:
    find -type f -not -name "*.gpg" | while read A; do
        gpg --batch --yes --trust-model always --encrypt --recipient "$REC" "$A"
    done
    
    # Moves files:
    DEST="$HOME/Dropbox/Temp Backup/Internet/Telegram"
    find -type f -name "*.gpg" | while read A; do
        D=$(dirname "$A")
        mkdir -p "$DEST/$D"
        mv "$A" "$DEST/$A"
    done
    
    # Removes processed media files:
    find media -type f | while read A; do
        rm "$A"
    done

At the moment, the conversations are not too big, and so there is no performance issue which would suggest using splitting.
