### ISSUE TITLE
Bad system call

### ISSUE THREAD

**Issue by Volteius** [tvdstaaij/telegram-history-dump#64]
When I run "telegram-cli --json -P 9009" all I get is a bad system call. How can I fix it?

**Comment by tvdstaaij** [comment]
This repository is not about telegram-cli (it's just a required external program) and I haven't seen this error before either. I suggest searching the issues or asking at [the telegram-cli repository](https://github.com/vysheng/tg).

**Comment by v3locite** [comment]
@Volteius , did you solve the problem?

**Comment by tvdstaaij** [comment]
I was wondering, does this only happen if the `-P` option is used? In that case using a socket file may be a workaround for the issue; this is supported since telegram-history-dump v2.3.0. See #56 for instructions, be sure to set the tg_sock option in the yaml config.

**Comment by v3locite** [comment]
Set as in change it to a port other than 9009? (which would you recommend)

**Comment by tvdstaaij** [comment]
No, I mean a unix socket file, which does not use a port number at all. You would use the -S option instead of the -P option (e.g. `telegram-cli -d -S /var/run/telegram.sock`). The same socket file path should then be configured in the tg_sock option in config.yaml. The configured port number is then ignored, because ports are irrelevant for this type of socket.

**Comment by Volteius** [comment]
Solved installing ubuntu and not using VirtualBox
